// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCilMspF17-_htyxrSVA_wIpRm9idrMCT8',
    appId: '1:303096540387:web:5b0dd3cbfa47171bf629d6',
    messagingSenderId: '303096540387',
    projectId: 'myfirstclass-753d7',
    authDomain: 'myfirstclass-753d7.firebaseapp.com',
    storageBucket: 'myfirstclass-753d7.firebasestorage.app',
    measurementId: 'G-7XZXZQSX8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByFmTQMmdZt1JZ2hyi5-N8WCPt9a6q7iM',
    appId: '1:303096540387:android:29e8202aa4ede3f4f629d6',
    messagingSenderId: '303096540387',
    projectId: 'myfirstclass-753d7',
    storageBucket: 'myfirstclass-753d7.firebasestorage.app',
  );
}
